# Generated by Django 5.1.3 on 2024-12-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
