# Generated by Django 5.1.3 on 2024-12-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Đang xử lý'), ('Shipping', 'Đang vận chuyển'), ('Delivered', 'Đã giao thành công'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=15),
        ),
    ]
