# Generated by Django 5.1.1 on 2024-12-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_productrecommendation_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProductRecommendation',
        ),
    ]
