# Generated by Django 5.1.1 on 2025-01-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_product_discounted_percent_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
