# Generated by Django 5.1.4 on 2025-01-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_product_discount_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_min', models.IntegerField()),
                ('height_max', models.IntegerField()),
                ('weight_min', models.IntegerField()),
                ('weight_max', models.IntegerField()),
                ('size', models.CharField(max_length=10)),
            ],
        ),
    ]
