# Generated by Django 5.1.4 on 2025-01-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_sizesuggestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SizeSuggestion',
        ),
    ]
