# Generated by Django 5.1.1 on 2025-01-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_delete_sizesuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng (COD)'), ('Online', 'Thanh toán online bằng quét mã QR')], max_length=10),
        ),
    ]
