# Generated by Django 5.1.4 on 2025-07-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ghn_order_code',
            field=models.CharField(blank=True, help_text='Mã vận đơn GHN', max_length=32, null=True),
        ),
    ]
