# Generated by Django 5.1.4 on 2025-07-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vnpay_response_code',
            field=models.CharField(blank=True, help_text='Mã phản hồi VNPAY', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vnpay_transaction_id',
            field=models.CharField(blank=True, help_text='Mã giao dịch VNPAY', max_length=64, null=True),
        ),
    ]
