# Generated by Django 5.1.4 on 2025-07-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_order_vnpay_response_code_order_vnpay_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng (COD)'), ('MoMo', 'Thanh toán online bằng quét mã QR'), ('VNPAY', 'Thanh toán online qua VNPAY')], max_length=10),
        ),
    ]
